/* Masala Ops analytics: quiet signal visualizations with explicit denominators and action-ready risk context. */
import { useEffect, useState } from "react";
import { ArrowUpRight, BarChart3, CircleAlert, Download, Info, Sparkles, TrendingUp, UsersRound } from "lucide-react";
import { Link } from "wouter";
import { toast } from "sonner";
import { Bar, BarChart, CartesianGrid, Cell, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Avatar, RiskChip, SectionLabel } from "@/components/SharedPrimitives";
import { candidates, funnelData, joiningWindow, recruiterStats } from "@/lib/mockData";
import { cn } from "@/lib/utils";

const chartTooltipStyle = { borderRadius: 12, border: "1px solid #eadcca", background: "#fffaf3", color: "#4a3428", fontSize: 11, boxShadow: "0 12px 24px rgba(91,57,36,0.08)" };

export default function Analytics() {
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(false);
  useEffect(() => { const timer = window.setTimeout(() => setLoading(false), 500); return () => window.clearTimeout(timer); }, []);
  if (loading) return <div className="space-y-7"><div className="h-32 animate-pulse rounded-[26px] bg-[#eadbca]" /><div className="grid gap-5 lg:grid-cols-2"><div className="h-80 animate-pulse rounded-[22px] bg-[#eadbca]" /><div className="h-80 animate-pulse rounded-[22px] bg-[#eadbca]" /></div></div>;
  if (error) return <div className="rounded-[22px] border border-[#efbdb0] bg-[#fff0eb] p-8 text-center"><CircleAlert className="mx-auto text-[#b44831]" /><p className="mt-3 text-sm font-extrabold text-[#8d3f2b]">Analytics could not be refreshed.</p><button onClick={() => setError(false)} className="mt-4 text-xs font-extrabold text-[#b44831] underline underline-offset-4">Retry</button></div>;

  return <div className="space-y-7">
    <section className="reveal-up relative flex flex-col justify-between gap-5 overflow-hidden rounded-[26px] border border-[#eadcca] bg-[#fbf7f0] p-6 shadow-[0_14px_34px_rgba(91,57,36,0.05)] sm:flex-row sm:items-end sm:p-8"><div className="absolute right-8 top-8 hidden h-24 w-24 rounded-full border border-[#eadcca] sm:block" /><div className="relative z-10"><SectionLabel>Signal room · 27 Aug 2026</SectionLabel><h2 className="display-face mt-3 text-[36px] leading-none text-[#3c2920] sm:text-[42px]">Know where the warmth drops<span className="text-[#f56a2a]">.</span></h2><p className="mt-3 max-w-2xl text-sm leading-6 text-[#806350]">A clear read on offer-to-join momentum, recruiter load, and the small set of people who need a better next touch.</p></div><button onClick={() => toast("Analytics export is coming soon") } className="focus-ring inline-flex items-center gap-2 self-start rounded-xl border border-[#dfcfbd] bg-[#fffaf3] px-3 py-2.5 text-[11px] font-extrabold text-[#735846] outline-none hover:border-[#f2a174] hover:text-[#f56a2a]"><Download size={14} /> Export report</button></section>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[{ value: "48", label: "Offered", note: "Across 3 teams", icon: UsersRound }, { value: "76%", label: "Offer → join", note: "+4.2% this quarter", icon: TrendingUp }, { value: "17", label: "Joining in 15d", note: "5 in final week", icon: BarChart3 }, { value: "6", label: "High-risk", note: "3 need a call", icon: CircleAlert }].map((item, index) => { const Icon = item.icon; return <div key={item.label} className={cn("reveal-up rounded-[20px] border border-[#eadcca] bg-[#fbf7f0] p-4 shadow-[0_10px_24px_rgba(91,57,36,0.04)]", `reveal-up-delay-${index + 1}`)}><div className="flex items-center justify-between"><span className="flex h-8 w-8 items-center justify-center rounded-xl bg-[#f3e2d2] text-[#a85c35]"><Icon size={15} /></span><ArrowUpRight size={14} className="text-[#c09a7d]" /></div><p className="display-face mt-5 text-[34px] leading-none text-[#3c2920]">{item.value}</p><p className="mt-2 text-xs font-extrabold text-[#5b4030]">{item.label}</p><p className="mt-1 text-[10px] font-semibold text-[#a38570]">{item.note}</p></div>; })}</section>
    <section className="grid gap-5 xl:grid-cols-[1.15fr_0.85fr]">
      <ChartCard title="Stage drop-off funnel" subtitle="Reached vs stalled at each journey step" label="Funnel"><ResponsiveContainer width="100%" height={285}><BarChart data={funnelData} layout="vertical" margin={{ top: 8, right: 12, bottom: 0, left: 4 }} barCategoryGap={12}><CartesianGrid horizontal={false} stroke="#eee1d1" /><XAxis type="number" hide domain={[0, 50]} /><YAxis type="category" dataKey="stage" width={92} tick={{ fill: "#876954", fontSize: 10, fontWeight: 700 }} tickLine={false} axisLine={false} /><Tooltip cursor={{ fill: "#faf1e6" }} contentStyle={chartTooltipStyle} /><Bar dataKey="reached" stackId="a" fill="#f56a2a" radius={[0, 4, 4, 0]} barSize={15} name="Reached" /><Bar dataKey="stalled" stackId="a" fill="#e8d7c5" radius={[0, 4, 4, 0]} barSize={15} name="Stalled" /></BarChart></ResponsiveContainer><div className="mt-4 flex flex-wrap items-center gap-4 text-[10px] font-bold text-[#987a65]"><span className="inline-flex items-center gap-1.5"><span className="h-2 w-2 rounded-full bg-[#f56a2a]" />Reached</span><span className="inline-flex items-center gap-1.5"><span className="h-2 w-2 rounded-full bg-[#e8d7c5]" />Stalled</span><span className="ml-auto inline-flex items-center gap-1"><Info size={12} />Based on 48 active offers</span></div></ChartCard>
      <ChartCard title="Joining window" subtitle="Candidates grouped by start week" label="Start dates"><ResponsiveContainer width="100%" height={285}><BarChart data={joiningWindow} margin={{ top: 16, right: 6, bottom: 0, left: -16 }}><CartesianGrid vertical={false} stroke="#eee1d1" /><XAxis dataKey="label" tick={{ fill: "#987a65", fontSize: 10, fontWeight: 700 }} tickLine={false} axisLine={false} /><YAxis tick={{ fill: "#b0927c", fontSize: 10 }} tickLine={false} axisLine={false} allowDecimals={false} /><Tooltip cursor={{ fill: "#faf1e6" }} contentStyle={chartTooltipStyle} /><Bar dataKey="candidates" fill="#6f9270" radius={[5, 5, 0, 0]} barSize={25} name="Candidates">{joiningWindow.map((item, index) => <Cell key={item.label} fill={index === 3 ? "#f56a2a" : "#82a481"} />)}</Bar></BarChart></ResponsiveContainer><div className="mt-4 flex items-center justify-between text-[10px] font-bold text-[#987a65]"><span className="inline-flex items-center gap-1.5"><span className="h-2 w-2 rounded-full bg-[#f56a2a]" />Peak week</span><span>34 planned joins shown</span></div></ChartCard>
    </section>
    <section className="grid gap-5 xl:grid-cols-[1.15fr_0.85fr]">
      <section className="reveal-up rounded-[22px] border border-[#eadcca] bg-[#fbf7f0] p-5 shadow-[0_12px_30px_rgba(91,57,36,0.05)] sm:p-7"><div className="flex items-end justify-between gap-3"><div><SectionLabel>Team pulse</SectionLabel><h3 className="display-face mt-2 text-[27px] leading-none text-[#3c2920]">Recruiter view</h3></div><span className="font-mono text-[9px] font-bold uppercase tracking-[0.12em] text-[#ae917c]">Rate / denominator</span></div><div className="mt-6 overflow-x-auto"><table className="w-full min-w-[560px] text-left"><thead><tr className="border-b border-[#eee2d3] font-mono text-[9px] font-bold uppercase tracking-[0.12em] text-[#b0927c]"><th className="pb-3">Recruiter</th><th className="pb-3">Join rate</th><th className="pb-3">In flight</th><th className="pb-3">High risk</th></tr></thead><tbody>{recruiterStats.map((stat) => <tr key={stat.name} className="border-b border-[#f0e6da] last:border-0"><td className="py-4"><div className="flex items-center gap-3"><Avatar initials={stat.initials} tone="cocoa" size="sm" /><span className="text-xs font-extrabold text-[#5b4030]">{stat.name}</span></div></td><td className="py-4"><p className="text-xs font-extrabold text-[#5b4030]">{stat.rate}%</p><p className="mt-1 text-[10px] font-semibold text-[#a38570]">{stat.joined} / {stat.offered} joined</p></td><td className="py-4 text-xs font-extrabold text-[#5b4030]">{stat.inFlight}</td><td className="py-4"><span className="inline-flex items-center gap-1.5 text-xs font-extrabold text-[#a6442e]"><span className="h-1.5 w-1.5 rounded-full bg-[#d8593d]" />{stat.highRisk}</span></td></tr>)}</tbody></table></div></section>
      <section className="reveal-up rounded-[22px] border border-[#efcbbb] bg-[#fff4eb] p-5 shadow-[0_12px_30px_rgba(245,106,42,0.06)] sm:p-7"><div className="flex items-center justify-between"><div><SectionLabel className="text-[#b26d48]">Needs a warmer touch</SectionLabel><h3 className="display-face mt-2 text-[27px] leading-none text-[#6f3825]">High-risk now</h3></div><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#f9d7bf] text-[#b44831]"><CircleAlert size={16} /></span></div><div className="mt-6 space-y-4">{candidates.filter((candidate) => candidate.risk === "high").slice(0, 4).map((candidate) => <Link key={candidate.id} href={`/candidates/${candidate.id}`} className="focus-ring group flex items-center gap-3 rounded-[16px] bg-[#fffaf3] p-3 outline-none"><Avatar initials={candidate.initials} tone="orange" size="sm" /><div className="min-w-0 flex-1"><p className="truncate text-xs font-extrabold text-[#5b4030] group-hover:text-[#f56a2a]">{candidate.name}</p><p className="mt-1 truncate text-[10px] font-semibold text-[#a38570]">{candidate.nextAction}</p></div><RiskChip risk={candidate.risk} /></Link>)}</div><div className="mt-6 flex items-center gap-2 border-t border-[#f0d5c5] pt-4 text-[10px] font-bold text-[#a56b4f]"><Sparkles size={13} /> Make one call before lunch.</div></section>
    </section>
  </div>;
}

function ChartCard({ title, subtitle, label, children }: { title: string; subtitle: string; label: string; children: React.ReactNode }) { return <section className="reveal-up rounded-[22px] border border-[#eadcca] bg-[#fbf7f0] p-5 shadow-[0_12px_30px_rgba(91,57,36,0.05)] sm:p-7"><div className="flex items-start justify-between gap-3"><div><SectionLabel>{label}</SectionLabel><div className="mt-2 flex items-center gap-2"><span className="h-1.5 w-9 rounded-full bg-[#f56a2a]" /><span className="h-1.5 w-1.5 rounded-full bg-[#f56a2a]" /><span className="h-1.5 w-1.5 rounded-full bg-[#decab6]" /><span className="h-1.5 w-1.5 rounded-full bg-[#decab6]" /></div><h3 className="display-face mt-3 text-[27px] leading-none text-[#3c2920]">{title}</h3><p className="mt-2 text-[11px] font-semibold text-[#a38570]">{subtitle}</p></div><span className="rounded-xl bg-[#f3eadf] p-2 text-[#aa8b75]"><BarChart3 size={15} /></span></div><div className="mt-6">{children}</div></section>; }
