/* Masala Ops task queue: a focused daily pass for open recruiter actions, not a second candidate list. */
import { useEffect, useMemo, useState } from "react";
import { ArrowUpRight, Check, ChevronRight, CircleAlert, Clock3, ListChecks, Sparkles, UserRound, X } from "lucide-react";
import { Link } from "wouter";
import { toast } from "sonner";
import { Avatar, SectionLabel } from "@/components/SharedPrimitives";
import { tasks as seedTasks, type Task } from "@/lib/mockData";
import { cn } from "@/lib/utils";
import { useNotifications } from "@/contexts/NotificationContext";

const groupMeta = {
  Overdue: { icon: CircleAlert, color: "text-[#b44831]", bg: "bg-[#fff0eb]", description: "Needs a human nudge before it becomes a blocker." },
  Today: { icon: Clock3, color: "text-[#a36c1d]", bg: "bg-[#fff6dd]", description: "The handful of actions that make today lighter." },
  Upcoming: { icon: Sparkles, color: "text-[#5d7c60]", bg: "bg-[#edf6e9]", description: "Keep these in rhythm while the rest moves forward." },
};

export default function Tasks() {
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(false);
  const [openTasks, setOpenTasks] = useState<Task[]>(seedTasks);
  const { addNotification } = useNotifications();
  useEffect(() => { const timer = window.setTimeout(() => setLoading(false), 430); return () => window.clearTimeout(timer); }, []);
  const grouped = useMemo(() => (["Overdue", "Today", "Upcoming"] as const).map((group) => ({ group, items: openTasks.filter((task) => task.dueGroup === group) })), [openTasks]);
  const complete = (id: string) => { setOpenTasks((current) => current.filter((task) => task.id !== id)); toast("Task completed — candidate stays on track"); };
  const dismiss = (id: string) => { setOpenTasks((current) => current.filter((task) => task.id !== id)); toast("Task dismissed"); };
  const assign = (task: Task) => { setOpenTasks((current) => current.map((item) => item.id === task.id ? { ...item, source: "human" } : item)); addNotification({ kind: "task", title: "Task assigned", body: `${task.action} for ${task.candidate} is now assigned to you.` }); };

  if (loading) return <div className="space-y-7"><div className="h-36 animate-pulse rounded-[26px] bg-[#eadbca]" /><div className="grid gap-4 lg:grid-cols-3">{[1, 2, 3].map((item) => <div key={item} className="h-72 animate-pulse rounded-[22px] bg-[#eadbca]" />)}</div></div>;
  if (error) return <div className="rounded-[22px] border border-[#efbdb0] bg-[#fff0eb] p-8 text-center"><CircleAlert className="mx-auto text-[#b44831]" /><p className="mt-3 text-sm font-extrabold text-[#8d3f2b]">The task queue took a pause.</p><button onClick={() => setError(false)} className="mt-4 text-xs font-extrabold text-[#b44831] underline underline-offset-4">Retry</button></div>;

  return <div className="space-y-7">
    <section className="reveal-up relative overflow-hidden rounded-[26px] bg-[#3c2920] p-6 text-[#fff9f0] shadow-[0_18px_42px_rgba(60,41,32,0.16)] sm:p-8"><div className="absolute -right-9 -top-12 h-48 w-48 rounded-full border-[18px] border-white/10" /><div className="absolute -bottom-20 right-20 h-48 w-48 rounded-full border-[1px] border-white/15" /><div className="relative max-w-2xl"><div className="flex items-center gap-2 font-mono text-[10px] font-bold uppercase tracking-[0.16em] text-[#ffe2d4]"><ListChecks size={14} /> The daily pass</div><h2 className="display-face mt-4 text-[36px] leading-none sm:text-[43px]">Do the next right thing<span className="text-[#f56a2a]">.</span></h2><p className="mt-3 max-w-xl text-sm leading-6 text-[#fff0e7]">{openTasks.length} open actions across the roster. Overdue first, then today, then the work that keeps joining day uneventful.</p><div className="mt-6 flex flex-wrap items-center gap-2"><span className="rounded-full bg-[#f56a2a] px-3 py-1.5 text-[10px] font-extrabold text-white">{grouped[0].items.length} overdue</span><span className="rounded-full bg-white/15 px-3 py-1.5 text-[10px] font-extrabold">{grouped[1].items.length} due today</span><span className="rounded-full bg-white/15 px-3 py-1.5 text-[10px] font-extrabold">{grouped[2].items.length} upcoming</span></div></div></section>
    <section className="grid gap-5 lg:grid-cols-3">{grouped.map(({ group, items }, index) => <TaskGroup key={group} group={group} items={items} index={index} onComplete={complete} onDismiss={dismiss} onAssign={assign} />)}</section>
    <div className="relative flex flex-col gap-3 overflow-hidden rounded-[20px] border border-[#eadcca] bg-[#fbf7f0] p-4 sm:flex-row sm:items-center sm:justify-between sm:p-5"><div className="relative z-10 flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-full bg-[#dbe8d6] text-[#557556]"><Check size={16} /></div><div><p className="text-xs font-extrabold text-[#4a3428]">A quiet queue is a good sign</p><p className="mt-1 text-[11px] text-[#a38570]">Completed work stays in the candidate's conversation history.</p></div></div><button onClick={() => toast("Task rules are coming soon") } className="focus-ring inline-flex items-center gap-1 self-start text-[11px] font-extrabold text-[#8a6a55] outline-none hover:text-[#f56a2a]">Manage task rules <ChevronRight size={14} /></button></div>
  </div>;
}

function TaskGroup({ group, items, index, onComplete, onDismiss, onAssign }: { group: keyof typeof groupMeta; items: Task[]; index: number; onComplete: (id: string) => void; onDismiss: (id: string) => void; onAssign: (task: Task) => void }) { const meta = groupMeta[group]; const Icon = meta.icon; return <section className={cn("reveal-up rounded-[22px] border border-[#eadcca] bg-[#fbf7f0] p-5 shadow-[0_12px_30px_rgba(91,57,36,0.05)]", `reveal-up-delay-${index + 1}`)}><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2"><span className={cn("flex h-8 w-8 items-center justify-center rounded-xl", meta.bg, meta.color)}><Icon size={15} /></span><h3 className="display-face text-[25px] leading-none text-[#3c2920]">{group}</h3></div><p className="mt-3 text-[11px] leading-5 text-[#a38570]">{meta.description}</p></div><span className={cn("rounded-full px-2 py-1 font-mono text-[9px] font-bold", meta.bg, meta.color)}>{items.length}</span></div><div className="mt-5 space-y-3">{items.length === 0 ? <div className="rounded-[16px] border border-dashed border-[#e4d5c3] px-4 py-7 text-center"><p className="text-xs font-extrabold text-[#6a4b39]">Nothing here</p><p className="mt-1 text-[10px] text-[#ad907b]">You have room for a good coffee.</p></div> : items.map((task) => <TaskCard key={task.id} task={task} onComplete={onComplete} onDismiss={onDismiss} onAssign={onAssign} />)}</div></section>; }

function TaskCard({ task, onComplete, onDismiss, onAssign }: { task: Task; onComplete: (id: string) => void; onDismiss: (id: string) => void; onAssign: (task: Task) => void }) { const accent = task.accent === "tomato" ? "border-l-[#d8593d]" : task.accent === "orange" ? "border-l-[#f56a2a]" : "border-l-[#79a079]"; return <article className={cn("group rounded-[16px] border border-[#eee1d1] border-l-4 bg-[#fffaf3] p-4 transition-all duration-200 hover:-translate-y-0.5 hover:shadow-[0_10px_20px_rgba(91,57,36,0.07)]", accent)}><div className="flex items-start gap-3"><Avatar initials={task.candidate.split(" ").map((part) => part[0]).join("")} tone={task.accent === "tomato" ? "orange" : task.accent === "sage" ? "sage" : "yellow"} size="sm" /><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><Link href={`/candidates/${task.candidateId}`} className="focus-ring text-xs font-extrabold text-[#4a3428] outline-none hover:text-[#f56a2a]">{task.candidate}</Link><span className="shrink-0 font-mono text-[9px] font-bold text-[#b0927c]">{task.dueLabel}</span></div><p className="mt-2 text-xs font-semibold leading-5 text-[#745744]">{task.action}</p><div className="mt-3 flex items-center justify-between"><span className="inline-flex items-center gap-1 rounded-md bg-[#f1e6d9] px-1.5 py-1 font-mono text-[9px] font-bold uppercase tracking-[0.06em] text-[#9c7b64]"><UserRound size={10} /> {task.source}</span><div className="flex items-center gap-1 opacity-0 transition-opacity group-hover:opacity-100">{task.source !== "human" ? <button onClick={() => onAssign(task)} aria-label={`Assign task for ${task.candidate}`} className="focus-ring rounded-lg p-1.5 text-[#a85c35] outline-none hover:bg-[#fff0e6]"><UserRound size={14} /></button> : null}<button onClick={() => onComplete(task.id)} aria-label={`Complete task for ${task.candidate}`} className="focus-ring rounded-lg p-1.5 text-[#67906b] outline-none hover:bg-[#e8f1e4]"><Check size={14} /></button><button onClick={() => onDismiss(task.id)} aria-label={`Dismiss task for ${task.candidate}`} className="focus-ring rounded-lg p-1.5 text-[#b99681] outline-none hover:bg-[#f6e8df]"><X size={14} /></button></div></div></div></div></article>; }
